//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promaker.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Promaker.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ds2 Promaker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재배치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoLayout {
            get {
                return ResourceManager.GetString("AutoLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자동 재배치 (Ctrl+L)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoLayoutTooltip {
            get {
                return ResourceManager.GetString("AutoLayoutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일괄편집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BatchEdit {
            get {
                return ResourceManager.GetString("BatchEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일괄 편집 (I/O, Duration)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BatchEditTooltip {
            get {
                return ResourceManager.GetString("BatchEditTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Call 추가 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CallAddFailed {
            get {
                return ResourceManager.GetString("CallAddFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloseFile {
            get {
                return ResourceManager.GetString("CloseFile", resourceCulture);
            }
        }

        /// <summary>
        ///   프로젝트 닫기 (Ctrl+Shift+W)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloseFileTooltip {
            get {
                return ResourceManager.GetString("CloseFileTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   현재 프로젝트에 저장되지 않은 변경이 있습니다.
        ///저장하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConfirmSaveChanges {
            get {
                return ResourceManager.GetString("ConfirmSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다크과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다크 테마 적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DarkThemeApplied {
            get {
                return ResourceManager.GetString("DarkThemeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteTooltip {
            get {
                return ResourceManager.GetString("DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   편집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV 내보내기...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExportCsv {
            get {
                return ResourceManager.GetString("ExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 열기 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileOpenFailed {
            get {
                return ResourceManager.GetString("FileOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 저장 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileSaveFailed {
            get {
                return ResourceManager.GetString("FileSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flow 추가 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FlowAddFailed {
            get {
                return ResourceManager.GetString("FlowAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work 리셋과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ForceWorkResetTooltip {
            get {
                return ResourceManager.GetString("ForceWorkResetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work 실행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ForceWorkStartTooltip {
            get {
                return ResourceManager.GetString("ForceWorkStartTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시간무시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IgnoreTime {
            get {
                return ResourceManager.GetString("IgnoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시간 무시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string IgnoreTimeTooltip {
            get {
                return ResourceManager.GetString("IgnoreTimeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라이트 테마 적용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LightThemeApplied {
            get {
                return ResourceManager.GetString("LightThemeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불러오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV 불러오기...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoadCsv {
            get {
                return ResourceManager.GetString("LoadCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불러오기 (Ctrl+O)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoadTooltip {
            get {
                return ResourceManager.GetString("LoadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 Call과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewCall {
            get {
                return ResourceManager.GetString("NewCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 파일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 파일 (Ctrl+N)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewFileTooltip {
            get {
                return ResourceManager.GetString("NewFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 Flow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewFlow {
            get {
                return ResourceManager.GetString("NewFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 프로젝트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 System과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewSystem {
            get {
                return ResourceManager.GetString("NewSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 Work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewWork {
            get {
                return ResourceManager.GetString("NewWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일시정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일시정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PauseSimulationTooltip {
            get {
                return ResourceManager.GetString("PauseSimulationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 속성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ProjectSettingsTooltip {
            get {
                return ResourceManager.GetString("ProjectSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다시실행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다시실행 (Ctrl+Y)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RedoTooltip {
            get {
                return ResourceManager.GetString("RedoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리포트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리포트 내보내기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReportTooltip {
            get {
                return ResourceManager.GetString("ReportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResetSimulationTooltip {
            get {
                return ResourceManager.GetString("ResetSimulationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다른 이름으로 저장...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장 확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveConfirmTitle {
            get {
                return ResourceManager.GetString("SaveConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다른 이름으로 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveFileAs {
            get {
                return ResourceManager.GetString("SaveFileAs", resourceCulture);
            }
        }

        /// <summary>
        ///   저장 (Ctrl+S)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveTooltip {
            get {
                return ResourceManager.GetString("SaveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flow를 선택해주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectFlow {
            get {
                return ResourceManager.GetString("SelectFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work를 선택해주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectWork {
            get {
                return ResourceManager.GetString("SelectWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Simulation {
            get {
                return ResourceManager.GetString("Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행 옵션과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SimulationOptions {
            get {
                return ResourceManager.GetString("SimulationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   속도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시뮬레이션 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartSimulationTooltip {
            get {
                return ResourceManager.GetString("StartSimulationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StopSimulationTooltip {
            get {
                return ResourceManager.GetString("StopSimulationTooltip", resourceCulture);
            }
        }



        /// <summary>
        ///   다크 테마로 전환과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SwitchToDarkTheme {
            get {
                return ResourceManager.GetString("SwitchToDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   라이트 테마로 전환과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SwitchToLightTheme {
            get {
                return ResourceManager.GetString("SwitchToLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System 추가 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemAddFailed {
            get {
                return ResourceManager.GetString("SystemAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도구과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   되돌리기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행취소 (Ctrl+Z)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UndoTooltip {
            get {
                return ResourceManager.GetString("UndoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경고과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work 추가 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WorkAddFailed {
            get {
                return ResourceManager.GetString("WorkAddFailed", resourceCulture);
            }
        }
    }
}
