<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Tests.fs" />
    <Compile Include="TemplateRoundTripTests.fs" />
    <Compile Include="MapperTests.fs" />
    <Compile Include="AasxProjectCacheTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
<PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\external\ds2\Solutions\Core\Ds2.Core\Ds2.Core.fsproj" />
    <ProjectReference Include="..\..\Core\Ds2.Editor\Ds2.Editor.fsproj" />
    <ProjectReference Include="..\..\..\external\ds2\Solutions\Convert\Ds2.Aasx\Ds2.Aasx.fsproj" />
    <ProjectReference Include="..\..\..\external\ds2\Solutions\Convert\Ds2.Mermaid\Ds2.Mermaid.fsproj" />
</ItemGroup>

</Project>
